/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as SpecialGameRouteImport } from './routes/special-game'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as PdfViewerRouteImport } from './routes/pdf-viewer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveClassRouteImport } from './routes/live-class'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FreeBoardRouteImport } from './routes/free-board'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClassmatesRouteImport } from './routes/classmates'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as BaniRouteImport } from './routes/bani'
import { Route as BangladeshMapRouteImport } from './routes/bangladesh-map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsSlugRouteImport } from './routes/subjects.$slug'
import { Route as ApiCloudinaryUploadRouteImport } from './routes/api/cloudinary-upload'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialGameRoute = SpecialGameRouteImport.update({
  id: '/special-game',
  path: '/special-game',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfViewerRoute = PdfViewerRouteImport.update({
  id: '/pdf-viewer',
  path: '/pdf-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveClassRoute = LiveClassRouteImport.update({
  id: '/live-class',
  path: '/live-class',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeBoardRoute = FreeBoardRouteImport.update({
  id: '/free-board',
  path: '/free-board',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassmatesRoute = ClassmatesRouteImport.update({
  id: '/classmates',
  path: '/classmates',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const BaniRoute = BaniRouteImport.update({
  id: '/bani',
  path: '/bani',
  getParentRoute: () => rootRouteImport,
} as any)
const BangladeshMapRoute = BangladeshMapRouteImport.update({
  id: '/bangladesh-map',
  path: '/bangladesh-map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSlugRoute = SubjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SubjectsRoute,
} as any)
const ApiCloudinaryUploadRoute = ApiCloudinaryUploadRouteImport.update({
  id: '/api/cloudinary-upload',
  path: '/api/cloudinary-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bangladesh-map': typeof BangladeshMapRoute
  '/bani': typeof BaniRoute
  '/certificates': typeof CertificatesRoute
  '/classmates': typeof ClassmatesRoute
  '/dashboard': typeof DashboardRoute
  '/free-board': typeof FreeBoardRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/live-class': typeof LiveClassRoute
  '/login': typeof LoginRoute
  '/pdf-viewer': typeof PdfViewerRoute
  '/quizzes': typeof QuizzesRoute
  '/special-game': typeof SpecialGameRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/cloudinary-upload': typeof ApiCloudinaryUploadRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bangladesh-map': typeof BangladeshMapRoute
  '/bani': typeof BaniRoute
  '/certificates': typeof CertificatesRoute
  '/classmates': typeof ClassmatesRoute
  '/dashboard': typeof DashboardRoute
  '/free-board': typeof FreeBoardRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/live-class': typeof LiveClassRoute
  '/login': typeof LoginRoute
  '/pdf-viewer': typeof PdfViewerRoute
  '/quizzes': typeof QuizzesRoute
  '/special-game': typeof SpecialGameRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/cloudinary-upload': typeof ApiCloudinaryUploadRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bangladesh-map': typeof BangladeshMapRoute
  '/bani': typeof BaniRoute
  '/certificates': typeof CertificatesRoute
  '/classmates': typeof ClassmatesRoute
  '/dashboard': typeof DashboardRoute
  '/free-board': typeof FreeBoardRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/live-class': typeof LiveClassRoute
  '/login': typeof LoginRoute
  '/pdf-viewer': typeof PdfViewerRoute
  '/quizzes': typeof QuizzesRoute
  '/special-game': typeof SpecialGameRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/cloudinary-upload': typeof ApiCloudinaryUploadRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bangladesh-map'
    | '/bani'
    | '/certificates'
    | '/classmates'
    | '/dashboard'
    | '/free-board'
    | '/games'
    | '/leaderboard'
    | '/library'
    | '/live-class'
    | '/login'
    | '/pdf-viewer'
    | '/quizzes'
    | '/special-game'
    | '/subjects'
    | '/api/chat'
    | '/api/cloudinary-upload'
    | '/subjects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bangladesh-map'
    | '/bani'
    | '/certificates'
    | '/classmates'
    | '/dashboard'
    | '/free-board'
    | '/games'
    | '/leaderboard'
    | '/library'
    | '/live-class'
    | '/login'
    | '/pdf-viewer'
    | '/quizzes'
    | '/special-game'
    | '/subjects'
    | '/api/chat'
    | '/api/cloudinary-upload'
    | '/subjects/$slug'
  id:
    | '__root__'
    | '/'
    | '/bangladesh-map'
    | '/bani'
    | '/certificates'
    | '/classmates'
    | '/dashboard'
    | '/free-board'
    | '/games'
    | '/leaderboard'
    | '/library'
    | '/live-class'
    | '/login'
    | '/pdf-viewer'
    | '/quizzes'
    | '/special-game'
    | '/subjects'
    | '/api/chat'
    | '/api/cloudinary-upload'
    | '/subjects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BangladeshMapRoute: typeof BangladeshMapRoute
  BaniRoute: typeof BaniRoute
  CertificatesRoute: typeof CertificatesRoute
  ClassmatesRoute: typeof ClassmatesRoute
  DashboardRoute: typeof DashboardRoute
  FreeBoardRoute: typeof FreeBoardRoute
  GamesRoute: typeof GamesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LibraryRoute: typeof LibraryRoute
  LiveClassRoute: typeof LiveClassRoute
  LoginRoute: typeof LoginRoute
  PdfViewerRoute: typeof PdfViewerRoute
  QuizzesRoute: typeof QuizzesRoute
  SpecialGameRoute: typeof SpecialGameRoute
  SubjectsRoute: typeof SubjectsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiCloudinaryUploadRoute: typeof ApiCloudinaryUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-game': {
      id: '/special-game'
      path: '/special-game'
      fullPath: '/special-game'
      preLoaderRoute: typeof SpecialGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-viewer': {
      id: '/pdf-viewer'
      path: '/pdf-viewer'
      fullPath: '/pdf-viewer'
      preLoaderRoute: typeof PdfViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-class': {
      id: '/live-class'
      path: '/live-class'
      fullPath: '/live-class'
      preLoaderRoute: typeof LiveClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-board': {
      id: '/free-board'
      path: '/free-board'
      fullPath: '/free-board'
      preLoaderRoute: typeof FreeBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classmates': {
      id: '/classmates'
      path: '/classmates'
      fullPath: '/classmates'
      preLoaderRoute: typeof ClassmatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bani': {
      id: '/bani'
      path: '/bani'
      fullPath: '/bani'
      preLoaderRoute: typeof BaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bangladesh-map': {
      id: '/bangladesh-map'
      path: '/bangladesh-map'
      fullPath: '/bangladesh-map'
      preLoaderRoute: typeof BangladeshMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$slug': {
      id: '/subjects/$slug'
      path: '/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof SubjectsSlugRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/api/cloudinary-upload': {
      id: '/api/cloudinary-upload'
      path: '/api/cloudinary-upload'
      fullPath: '/api/cloudinary-upload'
      preLoaderRoute: typeof ApiCloudinaryUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SubjectsRouteChildren {
  SubjectsSlugRoute: typeof SubjectsSlugRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSlugRoute: SubjectsSlugRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BangladeshMapRoute: BangladeshMapRoute,
  BaniRoute: BaniRoute,
  CertificatesRoute: CertificatesRoute,
  ClassmatesRoute: ClassmatesRoute,
  DashboardRoute: DashboardRoute,
  FreeBoardRoute: FreeBoardRoute,
  GamesRoute: GamesRoute,
  LeaderboardRoute: LeaderboardRoute,
  LibraryRoute: LibraryRoute,
  LiveClassRoute: LiveClassRoute,
  LoginRoute: LoginRoute,
  PdfViewerRoute: PdfViewerRoute,
  QuizzesRoute: QuizzesRoute,
  SpecialGameRoute: SpecialGameRoute,
  SubjectsRoute: SubjectsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiCloudinaryUploadRoute: ApiCloudinaryUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
